const SET_EMAIL = 'SET_EMAIL';
const SET_PASSWORD = 'SET_PASSWORD';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export { SET_EMAIL, SET_PASSWORD, SIGN_IN_SUCCESS, SIGN_IN_ERROR };
